<?php echo $this->assets->renderScripts();?>
<?php echo $this->assets->renderStyles();?>
<script>
    jQuery.noConflict();
</script>

<?php echo $this->renderTabs($this->tabs); ?>

<?php if ($this->error):?>
    <div class="msg-box msg-error">
         <div class="msg-content">
            <span class="title">Error:</span> <?php echo $this->error;?>
         </div>
    </div>
<?php endif;?>

<?php echo $this->form; ?>

<?php echo $this->partial('admin/footer.phtml');?>

<div class="modal fade" id="validationConfirm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Invalid template</h4>
                <h6 class="modal-explain">Your template contains some errors. Are you sure you want to save it with those errors?</h6>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="button" id="button-confirm" class="btn btn-primary" data-dismiss="modal">Save anyway</button>
            </div>
        </div>
    </div>
</div>