#!/usr/local/cpanel/3rdparty/bin/perl
use strict;

use lib '/usr/local/cpanel/whostmgr/docroot/cgi/KuberDock/libs';

use Cpanel::Logger ();
use Cpanel::PwCache ();
use KuberDock::Resellers;
use KuberDock::JSON;

use constant KUBERDOCK_CONFIG_PATH => '/var/cpanel/apps/kuberdock_whmcs.json';
 
my $stdin = <STDIN>;
chomp $stdin;
my ($uid, $function, $data) = split (/ /,$stdin,3);

my $user = (Cpanel::PwCache::getpwuid($uid))[0];
my $logger = Cpanel::Logger->new();
$logger->warn("KuberDock::Module::getConfig called by user $user with function: $function");

if($function eq 'getConfig') {
    if(-e KUBERDOCK_CONFIG_PATH) {
        my $resellers = KuberDock::Resellers->new;
        my $json = KuberDock::JSON->new;
        my $data = $resellers->loadData();
        $data->{defaults} = $resellers->loadDefaults;
        print $json->encode($data);
        exit(0);
    } else {
        print "KuberDock config file not exists. Please fill in 'Ressellers' tab via administrator interface";
        exit(1)
    }
} else {
    print "Invalid function specified to KuberDock::Module adminbin function";
    exit(1);
}

1;